/**
 * Contract-snapshot loading.
 *
 * The snapshot is generated by the SERVER repo (`pi-web-ui`,
 * scripts/generate-client-snapshot.ts) from its zod schemas and types, and is
 * committed there as docs/contract/internal-api-client-snapshot.json. The
 * client validates its builders and parsers against it.
 *
 * How the client learns of a NEWER snapshot:
 *   1. PI_ORCH_SNAPSHOT_PATH — explicit override (tests, pinned validation).
 *   2. The server main checkout's committed snapshot
 *      (/root/pi-web-ui/docs/contract/…) — regenerated whenever a server schema
 *      or type changes; the server repo's drift test fails CI otherwise.
 *   3. The bundled copy in this repo (contract/) — a fallback so the client
 *      works (and its tests pass) before a checkout carries the file.
 * Additionally at RUNTIME the client compares the snapshot's contractVersion
 * with the live GET /capabilities contract.contractVersion and surfaces
 * SNAPSHOT_STALE when they differ, so a parent knows its shape view may lag the
 * server it is talking to.
 */

import { existsSync, readFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { ZodField } from './zod-spec.ts';
import type { ExtractedType, SnapshotRoute } from './snapshot-types.ts';

export type { ZodField, ExtractedType, SnapshotRoute };

export interface ClientContractSnapshot {
  $schema: string;
  contractVersion: string;
  source: { typeFiles: string[]; zodFiles: string[]; routeFiles: string[] };
  errorCodes: string[];
  zodSchemas: Record<string, ZodField>;
  routes: Record<string, SnapshotRoute>;
  types: Record<string, ExtractedType>;
}

export type SnapshotSource = 'env' | 'server-checkout' | 'bundled';

export interface LoadedSnapshot {
  snapshot: ClientContractSnapshot;
  source: SnapshotSource;
  path: string;
}

const DEFAULT_SERVER_CHECKOUT = '/root/pi-web-ui';
const SNAPSHOT_RELATIVE = 'docs/contract/internal-api-client-snapshot.json';

/** Human-visible resolution order (also asserted by tests). */
export const SNAPSHOT_SEARCH_PATHS: readonly string[] = [
  '$PI_ORCH_SNAPSHOT_PATH',
  `${DEFAULT_SERVER_CHECKOUT}/${SNAPSHOT_RELATIVE}`,
  '<pi-orch repo>/contract/internal-api-client-snapshot.json',
];

const bundledPath = join(resolve(dirnameOfImportMeta(), '..'), 'contract', 'internal-api-client-snapshot.json');

function dirnameOfImportMeta(): string {
  return fileURLToPath(new URL('.', import.meta.url));
}

export function loadSnapshot(options: {
  env?: Record<string, string | undefined>;
  serverCheckoutRoot?: string;
  repoRoot?: string;
} = {}): LoadedSnapshot {
  const env = options.env ?? process.env;

  const override = env.PI_ORCH_SNAPSHOT_PATH;
  if (override) {
    return { ...readAndValidate(override), source: 'env' };
  }

  const serverRoot = options.serverCheckoutRoot ?? DEFAULT_SERVER_CHECKOUT;
  const serverPath = join(serverRoot, SNAPSHOT_RELATIVE);
  if (existsSync(serverPath)) {
    return { ...readAndValidate(serverPath), source: 'server-checkout' };
  }

  const fallback = options.repoRoot
    ? join(options.repoRoot, 'contract', 'internal-api-client-snapshot.json')
    : bundledPath;
  return { ...readAndValidate(fallback), source: 'bundled' };
}

function readAndValidate(path: string): { snapshot: ClientContractSnapshot; path: string } {
  let raw: string;
  try {
    raw = readFileSync(path, 'utf8');
  } catch (error) {
    throw new Error(
      `pi-orch: contract snapshot not readable at ${path} (search order: ${SNAPSHOT_SEARCH_PATHS.join(' -> ')})`,
      { cause: error },
    );
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (error) {
    throw new Error(`pi-orch: contract snapshot at ${path} is not valid JSON`, { cause: error });
  }
  assertSnapshotShape(parsed, path);
  return { snapshot: parsed as ClientContractSnapshot, path };
}

function assertSnapshotShape(value: unknown, path: string): void {
  const problems: string[] = [];
  if (typeof value !== 'object' || value === null) problems.push('not an object');
  else {
    const record = value as Record<string, unknown>;
    if (typeof record.contractVersion !== 'string' || !/^\d+\.\d+\.\d+$/.test(record.contractVersion)) {
      problems.push('contractVersion missing or not semver');
    }
    if (typeof record.routes !== 'object' || record.routes === null || Object.keys(record.routes as object).length === 0) {
      problems.push('routes missing or empty');
    }
    if (typeof record.types !== 'object' || record.types === null || Object.keys(record.types as object).length === 0) {
      problems.push('types missing or empty');
    }
    if (!Array.isArray(record.errorCodes) || record.errorCodes.length === 0) problems.push('errorCodes missing or empty');
    if (typeof record.zodSchemas !== 'object' || record.zodSchemas === null) problems.push('zodSchemas missing');
  }
  if (problems.length > 0) {
    throw new Error(`pi-orch: contract snapshot at ${path} is malformed: ${problems.join('; ')}`);
  }
}

/** Where the server's live contract version comes from (GET /capabilities). */
export function liveContractVersion(capabilities: unknown): string | undefined {
  if (typeof capabilities !== 'object' || capabilities === null) return undefined;
  const contract = (capabilities as { contract?: { contractVersion?: unknown } }).contract;
  const version = contract?.contractVersion;
  return typeof version === 'string' ? version : undefined;
}

export function defaultSocketPath(env: Record<string, string | undefined> = process.env): string {
  return env.PI_WEB_UI_SOCKET ?? join(homedir(), '.pi-web-ui', 'internal-api.sock');
}

export function defaultTokenPath(env: Record<string, string | undefined> = process.env): string {
  return env.PI_WEB_UI_TOKEN_PATH ?? join(homedir(), '.pi-web-ui', 'internal-api-token');
}
